- picker-compose/build.gradle.kts
- picker-compose/src/commonMain/kotlin/io/github/vinceglb/picker/compose/PickerCompose.kt
- picker-compose/src/jvmMain/kotlin/io/github/vinceglb/picker/compose/PickerCompose.jvm.kt
- picker-core/src/androidMain/kotlin/io/github/vinceglb/picker/core/Picker.android.kt
- picker-core/src/androidMain/kotlin/io/github/vinceglb/picker/core/PickerPlatformSettings.android.kt
- picker-core/src/appleMain/kotlin/io/github/vinceglb/picker/core/PickerPlatformSettings.apple.kt
- picker-core/src/commonMain/kotlin/io/github/vinceglb/picker/core/Picker.kt
- picker-core/src/commonMain/kotlin/io/github/vinceglb/picker/core/PickerPlatformSettings.kt
- picker-core/src/iosMain/kotlin/io/github/vinceglb/picker/core/Picker.ios.kt
- picker-core/src/jsMain/kotlin/io/github/vinceglb/picker/core/Picker.js.kt
- picker-core/src/jsMain/kotlin/io/github/vinceglb/picker/core/PickerPlatformSettings.js.kt
- picker-core/src/jvmMain/kotlin/io/github/vinceglb/picker/core/Picker.jvm.kt
- picker-core/src/jvmMain/kotlin/io/github/vinceglb/picker/core/PickerPlatformSettings.jvm.kt
- picker-core/src/jvmMain/kotlin/io/github/vinceglb/picker/core/platform/PlatformFilePicker.kt
- picker-core/src/jvmMain/kotlin/io/github/vinceglb/picker/core/platform/awt/AwtFilePicker.kt
- picker-core/src/jvmMain/kotlin/io/github/vinceglb/picker/core/platform/awt/AwtFileSaver.kt
- picker-core/src/jvmMain/kotlin/io/github/vinceglb/picker/core/platform/mac/MacOSFilePicker.kt
- picker-core/src/jvmMain/kotlin/io/github/vinceglb/picker/core/platform/windows/WindowsFilePicker.kt
- picker-core/src/macosMain/kotlin/io/github/vinceglb/picker/core/Picker.macos.kt
- picker-core/src/wasmJsMain/kotlin/io/github/vinceglb/picker/core/Picker.wasmJs.kt
- picker-core/src/wasmJsMain/kotlin/io/github/vinceglb/picker/core/PickerPlatformSettings.wasmJs.kt
> ✨ Introduce PickerPlatformSettings to enable JVM targets to handle the parent window

- build.gradle.kts
- samples/sample-compose/composeApp/build.gradle.kts
Resolved an inconsistency in JVM target compatibility between 'compileDebugJavaWithJavac' (11) and 'compileDebugKotlinAndroid' (17) by updating the compile options to use JVM target 17.
> ✏️ Fix compile error by modifying compileOptions and setting JVM target to 17

- README.md
I think you had a leftover "Picker Kotlin" from before the name change
> fix library name in README

- filekit-core/src/androidMain/kotlin/io/github/vinceglb/filekit/core/PlatformFile.android.kt
- filekit-core/src/appleMain/kotlin/io/github/vinceglb/filekit/core/PlatformFile.apple.kt
- filekit-core/src/commonMain/kotlin/io/github/vinceglb/filekit/core/PlatformFile.kt
- filekit-core/src/jsMain/kotlin/io/github/vinceglb/filekit/core/PlatformFile.js.kt
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/PlatformFile.jvm.kt
- filekit-core/src/wasmJsMain/kotlin/io/github/vinceglb/filekit/core/PlatformFile.wasmJs.kt
Added `fun getSize(): Long?` to `PlatformFile`. This allow accessing the size of a file without having to `readBytes` first.
> Feature/add getSize function to PlatformFile

- filekit-compose/src/androidMain/kotlin/io/github/vinceglb/filekit/compose/FileKitCompose.android.kt
Fixes #51
Don't initialize FileKit if the app is currently in inspection (preview) mode
> Don't init FileKit if in inspection mode

- filekit-core/build.gradle.kts
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/FileKit.jvm.kt
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/PlatformFilePicker.kt
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/awt/AwtFilePicker.kt
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/awt/AwtFileSaver.kt
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/mac/MacOSFilePicker.kt
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/windows/WindowsFilePicker.kt
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/xdg/XdgFilePickerPortal.kt
- gradle/libs.versions.toml
Adds support for Xdg Desktop File Chooser portal for Linux
https://flatpak.github.io/xdg-desktop-portal/docs/reasons-to-use-portals.html
https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html
It uses dbus-java which in turn uses Jvm implementation of domain unix sockets https://inside.java/2021/02/03/jep380-unix-domain-sockets-channels/ No additional native code added
If portal service is not available it will fallback to AWT filepciker
Tested on Ubuntu 22.04 with Gnome and on Archlinux with Kde Plasma
closes #64
> Xdg Desktop FileChooser Portal

- filekit-compose/src/androidMain/kotlin/io/github/vinceglb/filekit/compose/FileKitCompose.android.kt
- filekit-core/src/androidMain/kotlin/io/github/vinceglb/filekit/core/FileKit.android.kt
Fixes crashes on Android when rememberFilePickerLauncher() is called inside `androidx.compose.ui.window.Dialog`
When dialog is created Context is wrapped in `ContextThemeWrapper` and when attempt is made to cast it to `ComponentActivity` it crashes with `java.lang.ClassCastException`
Use `LocalActivityResultRegistryOwner` as a fix. 
It either stores a composition local instance of `ActivityResultRegistryOwner` or unwraps compositon local context until it finds activity that implements `ActivityResultRegistryOwner` (most oftent it is `ComponentActivity`)
Example to reproduce the crash:
``` kotlin
@Composable
fun App() {
MaterialTheme {
var showDialog by remember { mutableStateOf(false) }
Button(onClick = { showDialog = true }) {
Text("Show dialog")
}
if (showDialog) { …
```
> Fix crashes on Android inside Compose dialogs

- filekit-compose/build.gradle.kts
The `compose.desktop.currentOs` dependency should only be used in applications. This dependency also has an issue where it transitively brings in Material 2 compose dependency. That can lead to applications depending on FileKit to have both Material 3 and Material 2 in the classpath
> fix: remove unnecessary JVM dependency

- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/linux/LinuxFilePicker.kt
`saveFile()` isn't currently overridden in LinuxFilePicker, which causes it to open the default AWT dialog when saving files instead of trying to use the XDG picker. This overrides the method to follow the behavior of the other overrides.
> Override `saveFile()` in LinuxFilePicker

- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/xdg/XdgFilePickerPortal.kt
> Fix Map cast inside XDG ResponseHandler

- filekit-core/src/androidMain/kotlin/io/github/vinceglb/filekit/core/FileKit.android.kt
fix for https://github.com/vinceglb/FileKit/issues/117.
When overiding a fille with a smaller file in Android the file size would remain the same. Eg. 250kb file overriden with 200kb file, the file would continue being 250kb. This fix makes sure that we truncate the file before we change the bytes.
> remove extra bytes when overriding a file with a smaller file in android

- filekit-core/src/jsMain/kotlin/io/github/vinceglb/filekit/core/FileKit.js.kt
- filekit-core/src/wasmJsMain/kotlin/io/github/vinceglb/filekit/core/FileKit.wasmJs.kt
Hi!
I encountered a small bug while using FileKit for the JS target in Safari. To open the file picker programmatically in Safari, it is not enough to simply trigger a click on the input element. Safari doesn't always trigger the onchange event in this case. The input element must also be added to the DOM for the event to work properly.
This bug can be reproduced by running the following command:
./gradlew samples:sample-core:composeApp:jsBrowserDevelopmentRun
After running the command, attempt to upload a file in the Safari browser, and the issue will be evident.
Solution:
The solution is to add the file input element to the DOM and then remove it after the file(s) are processed or if the user cancels the upload. The input should be hidden visually as well, as display: none alone might …
> fix: trigger onchange event Safari

- filekit-dialogs/src/jvmMain/kotlin/io/github/vinceglb/filekit/dialogs/platform/awt/AwtFilePicker.kt
- filekit-dialogs/src/jvmMain/kotlin/io/github/vinceglb/filekit/dialogs/platform/swing/SwingFilePicker.kt
At least for `JFileChooser`, it looks like if multi-selection is disabled, then `getSelectedFiles()` won't return anything, and the single result will be in `getSelectedFile()`.
The Java documentation really isn't very explicit on this: the comment for `getSelectedFiles()` says
> Returns a list of selected files if the file chooser is set to allow multiple selection.
and doesn't mention that constraint anywhere else. But at least in some JDKs, `getSelectedFiles()` returns an empty array if multi-select is disabled, which breaks picking directories on Linux if the XDG picker isn't available.
Since I'm not sure that it's a good idea to rely on `isMultipleMode` for whether to use `getSelectedFiles()` or `getSelectedFile()`, I made the code use `getSelectedFiles()` and fall back to …
> fix: fall back to single `file` value if multi `files` value is empty in AWT and Swing

- filekit-core/build.gradle.kts
- filekit-core/src/androidMain/kotlin/io/github/vinceglb/filekit/PlatformFile.android.kt
- filekit-core/src/appleMain/kotlin/io/github/vinceglb/filekit/PlatformFile.apple.kt
- filekit-core/src/jvmAndNativeMain/kotlin/io/github/vinceglb/filekit/PlatformFile.jvmAndNative.kt
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/PlatformFile.jvm.kt
- filekit-core/src/nonWebMain/kotlin/io/github/vinceglb/filekit/PlatformFile.nonWeb.kt
Introduce new methods for iOS, macOS, JVM, Android:
- `PlatformFile.startAccessingSecurityScopedResource()`
- `PlatformFile.stopAccessingSecurityScopedResource()`
- `PlatformFile.withScopedAccess { }`
And improve file access control on iOS and macOS.
> Facilitate accessing iOS and macOS file information

- filekit-dialogs/src/jvmMain/kotlin/io/github/vinceglb/filekit/dialogs/platform/awt/AwtFilePicker.kt
- filekit-dialogs/src/jvmMain/kotlin/io/github/vinceglb/filekit/dialogs/platform/swing/SwingFilePicker.kt
I got a crash report in my app when using 0.10 beta 2 which reminded me that the singular `file`/`selectedFile` result of the Java pickers is nullable and needs to be handled properly, which I overlooked in my previous PR.
> fix: handle nullable file picker results

- filekit-dialogs/src/iosMain/kotlin/io/github/vinceglb/filekit/dialogs/FileKit.ios.kt
The `FileKit.openFileSaver` function throws a `kotlin.IllegalStateException: Failed to write to file URL` when the `suggestedName` contains a `/`.
The implemented fix replaces `/` with a valid character. I found [this discussion](https://discussions.apple.com/thread/677339) where they say `:` is rendered as `/` in the UI. I tested it on my iPhone and it seems to be true. I don't see any potential problem with `:`, but if you have another preference, we can choose a different character.
I also tested the macOS sample app, and the crash doesn't occur there, so this fix regards only iOS.
> 🐛 Fix openFileSaver on iOS when suggestedName contains "/"

- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/FileKit.jvm.kt
Use freedesktop basedir / userdir environment variables on Linux when available (#284) .
Added a check for the freedesktop variables on JVM / Linux with fallback to the previous values.
**⚠️ This is a breaking change for everyone relying on the previous values.**
@vinceglb Let me know if you need anyhing more, I couldn't find tests or other desktop specific code.
> ✨ Use freedesktop basedir / userdir on JVM linux

- filekit-dialogs/src/iosMain/kotlin/io/github/vinceglb/filekit/dialogs/FileKit.ios.kt
Fix `shareFile` on iOS to correctly share newly created files by ensuring a proper file URL is always provided to `UIActivityViewController`.
#306
> 🐛 Fix shareFile to use file URL

- filekit-dialogs/src/jvmMain/kotlin/io/github/vinceglb/filekit/dialogs/platform/xdg/XdgFilePickerPortal.kt
Fixes #239 
From the [docs](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html#org-freedesktop-portal-filechooser-openfile):
> `filters` `(a(sa(us)))`
> 
> List of serialized file filters.
> 
> Each item in the array specifies a single filter to offer to the user.
> 
> The first string is a user-visible name for the filter. The `a(us)` specifies a list of filter strings, which can be either a glob-style pattern (indicated by 0) or a MIME type (indicated by 1). Patterns are case-sensitive.
> 
> To match different capitalizations of, e.g. `'*.ico'`, use a pattern like: `'*.[iI][cC][oO]'`.
> 
> Example: `[('Images', [(0, '*.ico'), (1, 'image/png')]), ('Text', [(0, '*.txt')])]`
> 
> Note that filters are purely there to aid the user in making a …
> Add entry for all supported files on XDG

- filekit-core/src/androidMain/kotlin/io/github/vinceglb/filekit/PlatformFile.android.kt
- filekit-core/src/nonWebTest/kotlin/io/github/vinceglb/filekit/PlatformFileNonWebTest.kt
On Android, when writing to an existing file via URI, if the new data was shorter than existing content, leftover bytes from previous data remained. This occurred because openOutputStream(uri) defaults to append mode without truncation.
- Fix sink() method for AndroidFile.UriWrapper to use proper mode parameter
- Use "wt" (write+truncate) for non-append writes, "wa" for append writes
- Add test case to verify proper file truncation behavior
Related to #332
> 🐛 Fix Android file truncation when writing shorter content

- docs/dialogs/camera-picker.mdx
- docs/dialogs/share-file.mdx
- docs/snippets/android-fileprovider-setup.mdx
- Create reusable android-fileprovider-setup.mdx snippet
- Document FileKitOpenCameraSettings.authority usage for custom destinationFile
- Document FileKitShareSettings.authority usage for custom file locations
- Add 3-step Android setup guides for both camera-picker and share-file
- Improve documentation structure and reduce duplication
> 📝 Update FileProvider documentation with authority parameter usage

- docs/core/setup.mdx
- docs/snippets/setup-jvm-core.mdx
- Add ProGuard rules for JNA classes to setup-jvm-core.mdx snippet
- Move JVM setup section after Android setup for better organization
- Include platform-specific directory information in JVM snippet
> 📝 Add ProGuard configuration to JVM setup documentation

- docs/dialogs/open-file.mdx
- docs/dialogs/share-file.mdx
- docs/docs.json
- docs/snippets/android-fileprovider-setup.mdx
- Add comprehensive documentation for openFileWithDefaultApplication() feature
- Include Android FileProvider setup with security explanations
- Add code examples for different file types (PDF, images, text)
- Document error handling and platform-specific behavior
- Update navigation in docs.json to include new open-file page
- Refactor FileProvider setup into reusable snippet for consistency
> 📝 Add open file documentation for FileKit.openFileWithDefaultApplication()

- docs/snippets/setup-jvm-core.mdx
- filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/FileKit.jvm.kt
For applications that need custom directory paths (e.g., portable applications or specific deployment scenarios), you can specify custom cache and data directories:
```kotlin main.kt
fun main() {
val appDir = File(System.getProperty("user.home"), ".myapp")
FileKit.init(
appId = "MyApplication",
filesDir = File(appDir, "data"),
cacheDir = File(appDir, "cache")
)
// ...
}
```
> ✨ Add custom cache and files directories support for JVM FileKit

- filekit-dialogs/src/iosMain/kotlin/io/github/vinceglb/filekit/dialogs/FileKit.ios.kt
This change mitigates issues where certain files were not available for pickup.
Switch default file contentType: UTTypeContent -> UTTypeItem.
> Refactor: Switch default file contentType IOS
